In [157]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import SelectKBest, chi2

from sklearn.model_selection import train_test_split

from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

In [158]:
df = pd.read_csv("telecom_churn_mock_data.csv")

print("Dataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
df.head()

Dataset Shape:
(2000, 21)

First 5 Rows:

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST2999,Male,0,Yes,Yes,71,No,No,No,No,...,No,No,No,No,One year,No,Electronic check,120.00,8756.02,No
1,CUST2998,Male,0,No,No,19,Yes,No,No,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,84.09,1642.44,No
2,CUST2997,Male,0,No,No,57,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,No,Electronic check,82.28,4805.18,No
3,CUST2996,Female,0,No,Yes,34,Yes,No,DSL,No internet service,...,No internet service,No,No internet service,No,Month-to-month,Yes,Mailed check,120.00,3951.13,No
4,CUST2995,Female,0,No,Yes,72,Yes,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,No,Bank transfer (automatic),74.29,5206.46,No

In [159]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        2000 non-null   str
 1   Gender            2000 non-null   str
 2   SeniorCitizen     2000 non-null   int64
 3   Partner           2000 non-null   str
 4   Dependents        2000 non-null   str
 5   Tenure            2000 non-null   int64
 6   PhoneService      2000 non-null   str
 7   MultipleLines     2000 non-null   str
 8   InternetService   2000 non-null   str
 9   OnlineSecurity    2000 non-null   str
 10  OnlineBackup      2000 non-null   str
 11  DeviceProtection  2000 non-null   str
 12  TechSupport       2000 non-null   str
 13  StreamingTV       2000 non-null   str
 14  StreamingMovies   2000 non-null   str
 15  Contract          2000 non-null   str
 16  PaperlessBilling  2000 non-null   str
 17  PaymentMethod     2000 non-null   str
 18  MonthlyCharges    2000 non-null   float64
 19  TotalCharges      2000 non-null   float64
 20  Churn             2000 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 328.3 KB

In [160]:
df.describe()

       SeniorCitizen       Tenure  MonthlyCharges  TotalCharges
count    2000.000000  2000.000000     2000.000000   2000.000000
mean        0.151500    36.342500       65.880710   2394.132725
std         0.358625    21.029392       27.154716   1807.861046
min         0.000000     1.000000       18.000000     18.000000
25%         0.000000    18.000000       45.342500    934.712500
50%         0.000000    37.000000       65.460000   1972.770000
75%         0.000000    54.000000       84.992500   3532.675000
max         1.000000    72.000000      120.000000   8756.020000

In [161]:
print("Missing values")
df.isnull().sum()

Missing values

CustomerID          0
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [162]:
print("\n churn Distribution:")
print(df['Churn'].value_counts())

 churn Distribution:
Churn
No     1321
Yes     679
Name: count, dtype: int64

In [163]:
df.drop('CustomerID',axis=1,inplace= True)

In [164]:
print(df["Churn"].unique())

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [165]:
df = pd.read_csv("telecom_churn_mock_data.csv")
print(df["Churn"].unique())

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [166]:
df["Churn"] = df["Churn"].str.strip().str.lower()

In [167]:
df["Churn"] = df["Churn"].map({
    "yes": 1,
    "no": 0
})

In [168]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST2999,Male,0,Yes,Yes,71,No,No,No,No,...,No,No,No,No,One year,No,Electronic check,120.00,8756.02,0
1,CUST2998,Male,0,No,No,19,Yes,No,No,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,84.09,1642.44,0
2,CUST2997,Male,0,No,No,57,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,No,Electronic check,82.28,4805.18,0
3,CUST2996,Female,0,No,Yes,34,Yes,No,DSL,No internet service,...,No internet service,No,No internet service,No,Month-to-month,Yes,Mailed check,120.00,3951.13,0
4,CUST2995,Female,0,No,Yes,72,Yes,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,No,Bank transfer (automatic),74.29,5206.46,0

In [169]:
df=pd.get_dummies(df,drop_first=True)

In [170]:
df.head()

,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,Churn,CustomerID_CUST1001,CustomerID_CUST1002,CustomerID_CUST1003,CustomerID_CUST1004,CustomerID_CUST1005,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,71,120.00,8756.02,0,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,0,19,84.09,1642.44,0,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
2,0,57,82.28,4805.18,0,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
3,0,34,120.00,3951.13,0,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,True
4,0,72,74.29,5206.46,0,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [171]:
df['AvgMonthlySpend'] = (
    df['TotalCharges']
    /
    (df['Tenure'] + 1)
)

In [172]:
df['LongTermCustomer'] = np.where(
    df['Tenure'] > 24,
    1,
    0
)

In [173]:
df['HighValueCustomer'] = np.where(
    df['MonthlyCharges'] >
    df['MonthlyCharges'].median(),
    1,
    0
)

In [174]:
df.head()

,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,Churn,CustomerID_CUST1001,CustomerID_CUST1002,CustomerID_CUST1003,CustomerID_CUST1004,CustomerID_CUST1005,...,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,AvgMonthlySpend,LongTermCustomer,HighValueCustomer
0,0,71,120.00,8756.02,0,False,False,False,False,False,...,False,True,False,False,False,True,False,121.611389,1,1
1,0,19,84.09,1642.44,0,False,False,False,False,False,...,False,False,False,True,False,True,False,82.122000,0,1
2,0,57,82.28,4805.18,0,False,False,False,False,False,...,False,False,False,False,False,True,False,82.847931,1,1
3,0,34,120.00,3951.13,0,False,False,False,False,False,...,False,False,False,True,False,False,True,112.889429,1,1
4,0,72,74.29,5206.46,0,False,False,False,False,False,...,False,False,False,False,False,False,False,71.321370,1,1

In [175]:
X=df.drop('Churn',axis=1)
y=df['Churn']

In [176]:
selector = SelectKBest(
    score_func=chi2,
    k=20
)

X_selected = selector.fit_transform(X, y)

selected_features = X.columns[
    selector.get_support()
]

print("\nSelected Features:")
print(selected_features)

Selected Features:
Index(['Tenure', 'MonthlyCharges', 'TotalCharges', 'CustomerID_CUST2972',
       'CustomerID_CUST2973', 'CustomerID_CUST2976', 'CustomerID_CUST2978',
       'CustomerID_CUST2990', 'CustomerID_CUST2993',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'DeviceProtection_No internet service',
       'TechSupport_No internet service', 'Contract_One year',
       'Contract_Two year', 'AvgMonthlySpend', 'LongTermCustomer',
       'HighValueCustomer'],
      dtype='str')

In [177]:
X = df[selected_features]

In [178]:
X_train, X_test ,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [179]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [180]:
print(df["Churn"].value_counts())

Churn
0    1321
1     679
Name: count, dtype: int64

In [187]:
svm_model = SVC(
    kernel='rbf',
    probability=True,
    random_state=42
)

svm_model.fit(
    X_train,
    y_train
)

c:\Users\sindh\OneDrive\Desktop\ai-internes\venv\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVC(probability=True, random_state=42)

In [182]:
y_pred = svm_model.predict(X_test)

y_prob = svm_model.predict_proba(X_test)[:, 1]

In [183]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.6675

In [184]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)

Confusion Matrix:
[[255   9]
 [124  12]]

In [185]:
print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred
    )
)

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.97      0.79       264
           1       0.57      0.09      0.15       136

    accuracy                           0.67       400
   macro avg       0.62      0.53      0.47       400
weighted avg       0.64      0.67      0.58       400

In [186]:
auc = roc_auc_score(
    y_test,
    y_prob
)

print("\nROC-AUC Score:", auc)

ROC-AUC Score: 0.6428253119429591